### PR TITLE
create 21.08 branch

### PR DESCRIPTION
**Pull request by hfiguiere**
DO NOT MERGE 

the branch needs to be created manually

### CODE REVIEW

**Comment by hfiguiere** [comment]
The reason is that python llvmlite requires 11 specifically

**Comment by hfiguiere** [comment]
Just to clarify Piviti 22.06 has a new feature for decting beats, it needs `librosa` which require `numba` tha requires `llvmlite`, which in turn want llvm11 as most https://pypi.org/project/llvmlite/

**Comment by hfiguiere** [comment]
working on adding stage 1 bootstrap.

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
bot, build

**Comment by Erick555** [comment]
The easiest way may be to stop building with clang - removing [those](https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11/blob/adb7cf91cb133fa882544ba92fecee047da5eb8c/org.freedesktop.Sdk.Extension.llvm11.json#L103-L107) from manifest. Assuming old llvm is still buildable with new gcc.

**Comment by Erick555** [comment]
Alternatively minimal llvm can be build as app dependency. Extension may contain much more than necessary.

**Pull request closed without merging**
