### PR TITLE
Various improvements

### LINKED ISSUE #2: Why -DBUILD_SHARED_LIBS:BOOL=OFF and *.a in cleanup?
Hello,

So I was trying to build CastXML, it needed clang. I think this extension might provide it, but still fail.

```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/clang/ClangTargets.cmake:356 (message):
  The imported target "clangBasic" references the file

     "/usr/lib/x86_64-linux-gnu/libclangBasic.a"
```

I think that because -DBUILD_SHARED_LIBS:BOOL=OFF flag was use to generate static libs (.a) but was delete during cleanup.

```
      "cleanup": [
        "/include/lld",
        "*.a",
        "*.a.syms"
      ],
```

I think it should be -DBUILD_SHARED_LIBS:BOOL=ON?

### PR DESCRIPTION
**Pull request by Erick555**
- Add Clang and LLD static libs (Unlike LLVM, Clang and LLD may not have dynamic alternatives of static libs so keep them to make build certain things possible)
- Remove debug info (not critically important here, makes extension about 3 times smaller)
- Add clang-extra-tools and lldb to support more use cases

This results in 320MB size save while expanding available features significantly.

Fixes https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11/issues/2

### CODE REVIEW

**Comment by Erick555** [comment]
@gasinvein  @refi64 this may interest you.

**Comment by gasinvein** [comment]
To increase practical usefulness further, consider enabling `clang-tools-extra`. It'll add `clangd` - useful for IDEs.

**Comment by Erick555** [comment]
I'll look into it next. Do you have idea what's wrong with https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11/issues/2#issuecomment-793337792 ?

**Comment by gasinvein** [comment]
Didn't read it attentively, but I guess we shouldn't set `-DBUILD_SHARED_LIBS:BOOL=OFF` explicitly. Distro maintainers set this option for LLVM to invert their cmake default, but flatpak-builder doesn't have such.

**Comment by Erick555** [comment]
No, this option must be disabled, see https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11/issues/2#issuecomment-792948048

The problem is cmake doesn't look into extension path at all even after setting `prepend-path` and `prepend-ld-library-path` then try to use runtime llvm instead which doesn't have required libs. I hoped you dealt with similar issues through your sdk extensions experience 😄 .

**Comment by gasinvein** [comment]
I'm not very familiar with cmake and don't know for sure how it module search logic works, but probably `CMAKE_MODULE_PATH` or `LLVM_ROOT_DIR` should do. The later works for LDC.

**Comment by Erick555** [comment]
@gasinvein what do you think about passing `-g0` (disabling debug info)? I assume debugging the compiler itself isn't most wanted use case and this would allow adding features while keeping extension size reasonable. I think it's not possible to have separate .Debug extension of extension.

**Comment by gasinvein** [comment]
Oh wait. Stripping isn't enabled in `build-options`, is it? If so, I guess there is a big room for reducing size of the bundle.

**Comment by Erick555** [comment]
It isn't but strip will only work for shared libs not static which we introduce here (also why wasting build time to build debug symbols only to discard them just after). If removing debug symbols from shared libs is considered ok then I guess it's same for static libs.

**Comment by gasinvein** [comment]
I'd say dropping debug symbols is fine as long as the extension works properly most of the time (and doesn't need inspecting coredumps).

**Comment by Erick555** [comment]
@gasinvein I added clang-extra + lldb and ext size is still 320MB smaller than before adding static libs.

**Comment by Erick555** [comment]
@Lctrs could you review those changes? They improve extension and allow to build things otherwise unbuildable in flatpak.

**Comment by gasinvein** [comment]
@Erick555 Seem good. Did you test the resulting build?

**Comment by Erick555** [comment]
Static libs were confirmed working in https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11/issues/2#issuecomment-794056422 . The `-g0` added later shouldn't have any effect on that. I'm not much familiar with `clangd` or `lldb` myself so I leave anything beside invoking the binary (which works) to someone else. Testing much appreciated.

**Review by Lctrs — APPROVED** [review]

**Comment by Lctrs** [comment]
OK for me. Ready to be merged ?

**Comment by gasinvein** [comment]
I was thinking of testing this for builing QtCreator, but didn't get my hands on it yet.
Are there any apps on flathub that make use of this extension? If no, I guess merging it should be safe anyway.

**Comment by Lctrs** [comment]
There is none.

Initially, I made this extension for `net.rpcs3.RPSC3`, but couldn't make it work for various reasons.

**Comment by gasinvein** [comment]
Seems to work for QtCreator (it uses both LLVM and clang libs).

**Comment by gasinvein** [comment]
@Lctrs @Erick555  Oh, important side note: we should probably keep RPATH in place (i.e. drop `patches/llvm/llvm-no-rpath.patch`). Otherwise we can get broken ABI. E.g. `clangd` in this extension loads `libclang-cpp.so.11.1` from `.GL.default` extension, which is clearly invalid.

**Comment by Erick555** [comment]
How did you tested it? Can this be fixed with `LD_LIBRARY_PATH` env var or `prepend-ld-library-path`?

**Comment by gasinvein** [comment]
> How did you tested it?

With `ldd`.

>Can this be fixed with `LD_LIBRARY_PATH` env var or `prepend-ld-library-path`?

It can, but shouldn't. One will have to keep this in mind and manually setup it in their IDE.

**Comment by Erick555** [comment]
My concern is removing patch wouldn't fix that but I'll test. I think IDE have to do manual setup anyway because none of stuff from extension is in default paths (same is true for any extension).

**Comment by Erick555** [comment]
@gasinvein rust ext comes with [enable.sh script](https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable/blob/branch/20.08/org.freedesktop.Sdk.Extension.rust-stable.json#L158) that allows to easily setup environment. We can make similar thing here

**Comment by Erick555** [comment]
Sometinh like 
```
export PATH=/usr/lib/sdk/llvm11/bin:$PATH
export LD_LIBRARY_PATH=/usr/lib/sdk/llvm11/lib:$LD_LIBRARY_PATH
```

Then you just run ` source /usr/lib/sdk/llvm11/enable.sh` and everything works as it should.

**EDIT**: fixed wrong order above

**Comment by Lctrs** [comment]
Shouldn't they be prefixed so that they take precedence ?

**Comment by Erick555** [comment]
Yeah, sorry I made the order wrong.

**Comment by Erick555** [comment]
Adding RUNPATHS seems to work, I'll add enable.sh as well.

**Comment by gasinvein** [comment]
@Erick555 `enable.sh` works well only for one extension with libs. When there are multiple, they start to mix up on `LD_LIBRARY_PATH`. Also note that recent FD.o SDK adds extensions `lib/` subdir to ld search path anyway, so doing it in `enable.sh` is mostly pointless.
>My concern is removing patch wouldn't fix

AFAIK `RPATH` always takes precedence, so it should work.

**Comment by Erick555** [comment]
If it was pointless we didn't need to fix it 😄 . lvm11 ext is special because it overlaps with runtime (for now) and has to take precedence.

Anyway I set only `PATH` in `enable.sh` which is no-brainer.

**Comment by gasinvein** [comment]
> lvm11 ext is special because it overlaps with runtime (for now) and has to take precedence.

Yeah. The problem here is not missing libs, but the fact that the extension picks up wrong libs (they seems to be compatible ATM, but this can change any time).

**Pull request merged**
